# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-split" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "2e7e6dd4bd632ca54bcc50187ce5e097912ab616219088b81f0cafce6373910f"
      url "https://github.com/bcostea/claude-split/releases/download/v#{version}/claude-split_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dc2dc7763636645c8abbfe6f2026c41bef3452157c54000a3fd4c05c73bce869"
      url "https://github.com/bcostea/claude-split/releases/download/v#{version}/claude-split_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b0f779394d98d74af9284cba8eff0fe23ab2a60c4a4c71c0c78f3208f3263304"
      url "https://github.com/bcostea/claude-split/releases/download/v#{version}/claude-split_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c9bd92277ee921e7d19dec1e3a0fa6d9c84f927a51189c6b47e2072f407deb4a"
      url "https://github.com/bcostea/claude-split/releases/download/v#{version}/claude-split_linux_arm64.tar.gz"
    end
  end

  name "claude-split"
  desc "Manage multiple isolated Claude Code profiles, each with its own config and login"
  homepage "https://github.com/bcostea/claude-split"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-split"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-split"]
    end
  end

  # No zap stanza required

end
