# This file was generated by GoReleaser. DO NOT EDIT.
cask "macos-cli" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "bd9e47c9d647584836dafa5dc973bc1ffe0fc5b049ca90f905f8b2d2a10ed093"
      url "https://github.com/bcostea/macos-cli/releases/download/v#{version}/macos-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3a7c4ae9d55376f4c9e8c5d1ac6dd4b59ae7de222bf2e7e173eb6d14f204ce81"
      url "https://github.com/bcostea/macos-cli/releases/download/v#{version}/macos-cli_darwin_arm64.tar.gz"
    end
  end

  name "macos-cli"
  desc "Control macOS from the terminal — apps, windows, Finder, screenshots, notifications, system info"
  homepage "https://github.com/bcostea/macos-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "macos-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/macos-cli"]
    end
  end

  # No zap stanza required

end
